# STANDARD VALUES FOR THE PROGRAM

## COLOR THRESHOLDING
### IMAGES ARE IN GOOD CONDITION
GOOD_CONDITION = 1

### BLUE CELLS COLORS STANDARD
#### LOWER LIMITS
BLUE_CELL_LR = 0
BLUE_CELL_LG = 0
BLUE_CELL_LB = 120

#### UPPER LIMITS
BLUE_CELL_UR = 140
BLUE_CELL_UG = 140
BLUE_CELL_UB = 255

### BROWN CELLS COLORS STANDARD
#### LOWER LIMITS
BROWN_CELL_LR = 0
BROWN_CELL_LG = 0
BROWN_CELL_LB = 0

#### UPPER LIMITS
BROWN_CELL_UR = 255
BROWN_CELL_UG = 255
BROWN_CELL_UB = 110

## EDGE DETECTION METHOD
EDGE_DETECTION_TYPE = 1
EDGE_CANNY_LOWER = 75
EDGE_CANNY_UPPER = 100

## PERIMETER 
PERIMETER_MIN = 0
PERIMETER_MAX = 100

## CIRCULARITY
MIN_CIRCULARITY = 0.01
